// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	vaultOpen: (root: string, create: boolean | null) => typedError<VaultStatus, AppError>(__TAURI_INVOKE("vault_open", { root, create })),
	vaultStatus: () => typedError<VaultStatus, AppError>(__TAURI_INVOKE("vault_status")),
	/**  找当前 Vault 根目录的封面图（welcome.*，png 优先），返回绝对路径（无则 null）。 */
	vaultCover: () => typedError<string | null, AppError>(__TAURI_INVOKE("vault_cover")),
	/**
	 *  把内嵌的欢迎库默认封面写到指定 vault 根目录（welcome.jpg）。
	 *  已有同名文件则跳过（用户自定义的封面不被覆盖）；返回是否实际写入。
	 */
	welcomeCoverWrite: (root: string) => typedError<boolean, AppError>(__TAURI_INVOKE("welcome_cover_write", { root })),
	notesList: () => typedError<NoteSummaryDto[], AppError>(__TAURI_INVOKE("notes_list")),
	notesRead: (path: string) => typedError<ReadNoteResponse, AppError>(__TAURI_INVOKE("notes_read", { path })),
	notesBacklinks: (target: string) => typedError<BacklinkDto[], AppError>(__TAURI_INVOKE("notes_backlinks", { target })),
	notesSave: (req: SaveNoteRequest) => typedError<SaveNoteResponse, AppError>(__TAURI_INVOKE("notes_save", { req })),
	notesCreate: (req: CreateNoteRequest) => typedError<SaveNoteResponse, AppError>(__TAURI_INVOKE("notes_create", { req })),
	/**
	 *  把"抢救 LOCAL"和"重读磁盘最新版本"合成一次原子操作：
	 *  1. 先把 LOCAL 写入 history（source=conflict-discard）——失败则整条 Err
	 *  2. 再读取磁盘当前内容
	 *  单次调用的保证：snapshot 失败时 LOCAL 不会被丢弃、磁盘内容也不会被错读；
	 *  前端拿到 Err 时缓冲区保持不变，状态机仍为 conflict。
	 */
	notesDiscardLocalAndReload: (req: DiscardLocalRequest) => typedError<ReadNoteResponse, AppError>(__TAURI_INVOKE("notes_discard_local_and_reload", { req })),
	/**  删除笔记。内容已先抢救进 history，可恢复。 */
	notesDelete: (req: DeleteNoteRequest) => typedError<PathChangesResponse, AppError>(__TAURI_INVOKE("notes_delete", { req })),
	/**  重命名/移动笔记。返回旧→新映射，前端更新打开的编辑器。 */
	notesRename: (req: RenameNoteRequest) => typedError<PathChangesResponse, AppError>(__TAURI_INVOKE("notes_rename", { req })),
	/**  删除目录：目录下所有笔记先抢救进 history 再整体移除。 */
	notesDeleteDir: (req: DeleteDirRequest) => typedError<PathChangesResponse, AppError>(__TAURI_INVOKE("notes_delete_dir", { req })),
	/**  重命名目录：目录下全部笔记路径前缀替换，返回受影响映射。 */
	notesRenameDir: (req: RenameDirRequest) => typedError<PathChangesResponse, AppError>(__TAURI_INVOKE("notes_rename_dir", { req })),
};

/** Events */
export const events = {
	fileChanged: makeEvent<FileChanged>("file-changed"),
	treeChanged: makeEvent<TreeChanged>("tree-changed"),
};

/* Types */
/**  统一 IPC 错误。领域/IO 错误的具体类型永不穿越 IPC 边界。 */
export type AppError = { type: "NotFound"; path: string } | { type: "AlreadyExists"; path: string } | { type: "Conflict"; path: string; expected: string; actual: string } | { type: "InvalidEncoding"; path: string } | { type: "PathOutsideVault"; detail: string } | { type: "VaultNotOpen" } | { type: "Io"; detail: string };

export type BacklinkDto = {
	source_path: string,
	target: string,
	heading: string | null,
	alias: string | null,
};

export type CreateNoteRequest = {
	path: string,
	content: string,
};

export type DeleteDirRequest = {
	dir: string,
};

export type DeleteNoteRequest = {
	path: string,
};

export type DiscardLocalRequest = {
	path: string,
	/**  即将被丢弃的编辑器缓冲内容 */
	content: string,
};

export type DiskKind = "content" | "deleted" | "unreadable";

/**
 *  单文件内容变化（外部修改热重载/冲突检测）。
 *  disk_kind 三态：content = 正常内容（content 字段为归一化文本）；
 *  deleted = 文件被外部删除；unreadable = 文件在但无法加载（非法 UTF-8 等）。
 */
export type FileChanged = {
	path: string,
	content_hash: string,
	/**  见结构体注释；与 content 字段联动：content 仅为 Some 当且仅当 kind == content */
	disk_kind: DiskKind,
	content: string | null,
};

export type NoteSummaryDto = {
	/**  Vault 相对路径，`/` 分隔 */
	path: string,
	/**  字节数（u32：单文件 4GB 上限对 Markdown 笔记足够） */
	size: number,
	/**  修改时间（Unix 毫秒，f64 承载至 2286 年无精度损失） */
	modified_ms: number | null,
};

/**
 *  rename/delete 的结果：受影响路径映射 + 提示性原因。
 *  前端据此更新打开的编辑器（旧路径 → 新路径）或关闭已删的缓冲区。
 */
export type PathChangesResponse = {
	/**  旧路径 → 新路径（delete 时值为空） */
	moved: PathMove[],
	/**  被删除的路径 */
	deleted: string[],
};

export type PathMove = {
	from: string,
	to: string,
};

export type ReadNoteResponse = {
	path: string,
	/**  归一化后内容（LF、无 BOM） */
	content: string,
	/**  原始磁盘字节 SHA-256（保存时作为 expected_hash 传回） */
	content_hash: string,
	/**  该笔记内的 wikilink 出链（target + heading + alias） */
	links: WikiLinkDto[],
};

export type RenameDirRequest = {
	from: string,
	to: string,
};

export type RenameNoteRequest = {
	from: string,
	to: string,
};

export type SaveNoteRequest = {
	path: string,
	content: string,
	expected_hash: string,
};

export type SaveNoteResponse = {
	path: string,
	new_content_hash: string,
};

/**  文件树结构变化（新建/删除/重命名后触发前端刷新） */
export type TreeChanged = {
	/**  变化原因（提示性，非事实源） */
	reason: string,
};

export type VaultStatus = {
	open: boolean,
	/**  Vault 根的绝对路径（未打开为 None） */
	root: string | null,
};

export type WikiLinkDto = {
	target: string,
	heading: string | null,
	alias: string | null,
	/**  起始/结束字节偏移（文档内） */
	span_from: number,
	span_to: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

