// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	vaultOpen: (root: string) => typedError<VaultStatus, AppError>(__TAURI_INVOKE("vault_open", { root })),
	vaultStatus: () => typedError<VaultStatus, AppError>(__TAURI_INVOKE("vault_status")),
	notesList: () => typedError<NoteSummaryDto[], AppError>(__TAURI_INVOKE("notes_list")),
	notesRead: (path: string) => typedError<ReadNoteResponse, AppError>(__TAURI_INVOKE("notes_read", { path })),
	notesBacklinks: (target: string) => typedError<BacklinkDto[], AppError>(__TAURI_INVOKE("notes_backlinks", { target })),
	notesSave: (req: SaveNoteRequest) => typedError<SaveNoteResponse, AppError>(__TAURI_INVOKE("notes_save", { req })),
	notesCreate: (req: CreateNoteRequest) => typedError<SaveNoteResponse, AppError>(__TAURI_INVOKE("notes_create", { req })),
	/**
	 *  冲突抢救：把即将被丢弃的本地版本写入 history（source=conflict-discard），
	 *  然后前端再执行"重新读取"。契约 §4.5：丢弃前必须已入恢复存储。
	 */
	notesDiscardLocal: (req: DiscardLocalRequest) => typedError<SaveNoteResponse, AppError>(__TAURI_INVOKE("notes_discard_local", { req })),
};

/** Events */
export const events = {
	fileChanged: makeEvent<FileChanged>("file-changed"),
	treeChanged: makeEvent<TreeChanged>("tree-changed"),
};

/* Types */
/**  统一 IPC 错误。领域/IO 错误的具体类型永不穿越 IPC 边界。 */
export type AppError = { type: "NotFound"; path: string } | { type: "AlreadyExists"; path: string } | { type: "Conflict"; path: string; expected: string; actual: string } | { type: "InvalidEncoding"; path: string } | { type: "PathOutsideVault"; detail: string } | { type: "VaultNotOpen" } | { type: "Io"; detail: string };

export type BacklinkDto = {
	source_path: string,
	target: string,
	heading: string | null,
	alias: string | null,
};

export type CreateNoteRequest = {
	path: string,
	content: string,
};

export type DiscardLocalRequest = {
	path: string,
	/**  即将被丢弃的编辑器缓冲内容 */
	content: string,
};

/**
 *  单文件内容变化（外部修改热重载/冲突检测）。
 *  content = None 表示文件被外部删除。
 */
export type FileChanged = {
	path: string,
	content_hash: string,
	content: string | null,
};

export type NoteSummaryDto = {
	/**  Vault 相对路径，`/` 分隔 */
	path: string,
	/**  字节数（u32：单文件 4GB 上限对 Markdown 笔记足够） */
	size: number,
	/**  修改时间（Unix 毫秒，f64 承载至 2286 年无精度损失） */
	modified_ms: number | null,
};

export type ReadNoteResponse = {
	path: string,
	/**  归一化后内容（LF、无 BOM） */
	content: string,
	/**  原始磁盘字节 SHA-256（保存时作为 expected_hash 传回） */
	content_hash: string,
	/**  该笔记内的 wikilink 出链（target + heading + alias） */
	links: WikiLinkDto[],
};

export type SaveNoteRequest = {
	path: string,
	content: string,
	expected_hash: string,
};

export type SaveNoteResponse = {
	path: string,
	new_content_hash: string,
};

/**  文件树结构变化（新建/删除/重命名后触发前端刷新） */
export type TreeChanged = {
	/**  变化原因（提示性，非事实源） */
	reason: string,
};

export type VaultStatus = {
	open: boolean,
	/**  Vault 根的绝对路径（未打开为 None） */
	root: string | null,
};

export type WikiLinkDto = {
	target: string,
	heading: string | null,
	alias: string | null,
	/**  起始/结束字节偏移（文档内） */
	span_from: number,
	span_to: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

